config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root :to => 'homes#top'
  get "homes/show" => "homes#show"
  resources :users, only: [:show, :edit, :update, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user, optional: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2 }
  validates :name, length: {maximum: 20 }
  validates :profile, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:index, :edit]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
        flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(book.id)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
  params.require(:user).permit(:name, :profile_image, :profile)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
       render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :profile)
  end

end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@book, local:true do |f| %>

  <label>Title</label>
  <div class="field">
  <%= f.text_field :title %>
  </div>

  <label>Body</label>
  <div class="field">
  <%= f.text_area :body %>
  </div>
  <div class="action">
  <%= f.submit 'Update Book' %>
  </div>

<% end %>

  <%= link_to "Show", books_path(@book) %>
  |
  <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="header">
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user users"> Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book books"> Books</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out logout"> logout</span>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
                <span class="glyphicon glyphicon-link about"> About</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <span class="glyphicon glyphicon-edit sign_up"> sign up</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <span class="glyphicon glyphicon-log-in sign_in"> login</span>
              <% end %>
            </li>

          <% end %>
        </ul>
      </nav>
    </div>
  </header>
</div>

<div>
  <% if @book.errors.any? %>
  <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
  </ul>
  <% end %>
</div>



<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<div class="body">
  <div class="container">
    <div class="row">
      <%= render 'users/left-bar', user: @user, book: @book %>

      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Opinion</th>
                </tr>
              </thead>
              <tbody>
                <%  @books.each do |book|  %>
                <tr>
                  <td><%= link_to book.title, book_path(book) %></td>
                  <td><%= book.body %></td>
                </tr>
                <% end %>
              </tbody>
        </table>
    　</div>

    </div>
  </div>
</div>

<%= render 'users/footer' %>

app/views/books/show.html.erb
 <div class="header">
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to user_path(current_user.id) do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user users"> Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book books"> Books</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out logout"> logout</span>
              <% end %>
            </li>
        </ul>
      </nav>
    </div>
  </header>
</div>

<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>


<div class="body">
  <div class="container">
    <div class="row">


      <%= render 'users/left-bar', user: @user, book: @book %>

      <div class="col-xs-9">

        <h2>Book detail</h2>

        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, :size =>'40x40', fallback: "no_image.jpg" %><br>
                  <%= @user.name %>
                <% end %>
              </td>
              <td>
                <%= @book.title %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to edit_book_path(@book) do %>
                      <span class="btn-sm btn-success edit_book_44130">Edit</span>
                    <% end %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"} do %>
                    <span class="btn-sm btn-danger destroy_book_44130">Destroy</span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

      </div>

    </div>
  </div>
</div>

<%= render 'users/footer' %>

app/views/homes/show.html.erb
<div class="header">
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <span class="glyphicon glyphicon-user users"> Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book books"> Books</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out logout"> logout</span>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to homes_show_path do %>
                <span class="glyphicon glyphicon-link about"> About</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <span class="glyphicon glyphicon-edit sign_up"> sign up</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <span class="glyphicon glyphicon-log-in sign_in"> login</span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
</div>

<div class="body">
  <div class="container">
    <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
  </div>
</div>

<%= render 'users/footer' %>

app/views/homes/top.html.erb
<div class="header">
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <span class="glyphicon glyphicon-user users"> Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book books"> Books</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out logout"> logout</span>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path do %>
                <span class="glyphicon glyphicon-home home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to homes_show_path do %>
                <span class="glyphicon glyphicon-link about"> About</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <span class="glyphicon glyphicon-edit sign_up"> sign up</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <span class="glyphicon glyphicon-log-in sign_in"> login</span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
</div>

<div class="body">
  <div class="container">

    <h1>
      welcome to<span class="glyphicon glyphicon-book"><strong>Bookers </strong></span>!!
    </h1>
    <p>In <span class="glyphicon glyphicon-book"><strong>Bookers </strong></span></p>
    <p>you can share and exchange your opinions , impressions , and emotions</p>
    <p>about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
          <%= link_to new_user_session_path do %>
            <p class="btn btn-info col-xs-10 col-xs-offset-1 sign_in"> Log in</p>
          <% end %>
      </div>
      <div class="row">
          <%= link_to new_user_registration_path do %>
            <span class="btn btn-success col-xs-10 col-xs-offset-1 sign_up"> Sign up</span>
          <% end %>
      </div>
    </div>

  </div>
</div>

<%= render 'users/footer' %>